### ISSUE TITLE
call method:"decompressFileAtPath:toPath:error:" crash

### ISSUE THREAD

**Issue by QF-ZhouCheng** [daltoniam/tarkit#9] opened 2016-01-26 09:39 UTC
when call the method and give a error parameters will crash.

like this:
``` Objective-C
NSError *decompressError = nil;
[DCTar decompressFileAtPath:strOfflineH5Path toPath:_strOfflinePath error:nil];
```

you can try it.

**Comment by daltoniam** [comment] 2016-01-27 02:48
duplicate of #10

**Closed by daltoniam** 2016-01-27 02:48 UTC
